package com.portway.core.generate;

import com.portway.core.ir.MethodDecl;
import com.portway.core.ir.SourceFile;
import com.portway.core.ir.TypeDecl;
import com.portway.core.report.Finding;
import com.portway.core.report.FindingCode;
import com.portway.core.report.MethodReport;
import com.portway.core.report.Strategy;
import java.util.Comparator;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Collectors;

/**
 * MIGRATION-NOTES.md: the reviewer's checklist, written into the generated project itself.
 *
 * <p>It exists so the work that remains travels with the code rather than living only in the
 * Portway UI: the stubbed methods with their reasons, every finding grouped by code, and the EF
 * fluent configuration copied verbatim because it was deliberately not translated.
 */
public class MigrationNotesGenerator {

  /** A DbContext whose OnModelCreating was not translated, with its source location. */
  public record FluentConfiguration(TypeDecl context, SourceFile source, MethodDecl method) {}

  public GeneratedFile generate(
      String projectName,
      List<MethodReport> methods,
      List<Finding> findings,
      List<FluentConfiguration> fluent) {

    StringBuilder md = new StringBuilder();
    md.append("# Migration notes: ").append(projectName).append("\n\n");
    md.append("Generated by Portway. Everything below needs a human decision before this project")
        .append(" is trusted.\n\n");

    Map<Strategy, Long> byStrategy = new EnumMap<>(Strategy.class);
    for (MethodReport m : methods) {
      byStrategy.merge(m.strategy(), 1L, Long::sum);
    }
    md.append("## Summary\n\n");
    md.append("| Methods | Count |\n|---|---|\n");
    for (Strategy s : Strategy.values()) {
      md.append("| ").append(label(s)).append(" | ").append(byStrategy.getOrDefault(s, 0L)).append(" |\n");
    }
    md.append("| **Total** | ").append(methods.size()).append(" |\n\n");

    List<MethodReport> manual =
        methods.stream().filter(m -> m.strategy() == Strategy.MANUAL_REQUIRED).toList();
    md.append("## Methods to finish by hand\n\n");
    if (manual.isEmpty()) {
      md.append("None.\n\n");
    } else {
      md.append("Each is stubbed with `UnsupportedOperationException` and carries the original C#")
          .append(" in its Javadoc.\n\n");
      md.append("| Method | Source | Reason |\n|---|---|---|\n");
      for (MethodReport m : manual) {
        md.append("| `").append(m.javaClassName()).append('.').append(m.javaSignature().replaceAll(".* (\\w+\\()", "$1"))
            .append("` | ").append(m.sourcePath()).append(':').append(m.startLine())
            .append(" | ").append(escape(m.reason())).append(" |\n");
      }
      md.append('\n');
    }

    md.append("## Findings\n\n");
    if (findings.isEmpty()) {
      md.append("None.\n\n");
    }
    Map<FindingCode, List<Finding>> byCode =
        findings.stream()
            .collect(Collectors.groupingBy(Finding::code, () -> new TreeMap<>(
                Comparator.comparing((FindingCode c) -> c.defaultSeverity().ordinal())
                    .thenComparing(Enum::name)), Collectors.toList()));
    for (Map.Entry<FindingCode, List<Finding>> group : byCode.entrySet()) {
      md.append("### ").append(group.getKey().name()).append(" (")
          .append(group.getKey().defaultSeverity()).append(", ").append(group.getValue().size())
          .append(")\n\n");
      for (Finding f : group.getValue()) {
        md.append("- ").append(escape(f.message()));
        if (f.sourcePath() != null) {
          md.append(" `").append(f.sourcePath());
          if (f.sourceLine() > 0) {
            md.append(':').append(f.sourceLine());
          }
          md.append('`');
        }
        md.append('\n');
      }
      md.append('\n');
    }

    if (!fluent.isEmpty()) {
      md.append("## Manual: EF fluent configuration\n\n");
      md.append("Not translated. Index, cascade and key rules written here have JPA equivalents")
          .append(" that depend on intent; compare each against the generated entities.\n\n");
      for (FluentConfiguration f : fluent) {
        md.append("### ").append(f.context().name()).append(".OnModelCreating (")
            .append(f.source().path()).append(':').append(f.method().startLine()).append(")\n\n");
        md.append("```csharp\n").append(MethodEmitter.csharpSource(f.method())).append("\n```\n\n");
      }
    }
    return new GeneratedFile("MIGRATION-NOTES.md", md.toString(), null, List.of());
  }

  private static String label(Strategy s) {
    return switch (s) {
      case RULE_MAPPED -> "Translated by rules";
      case AI_VERIFIED -> "Translated by AI, compiled first time";
      case AI_REPAIRED -> "Translated by AI after one repair";
      case MANUAL_REQUIRED -> "Stubbed for manual migration";
    };
  }

  private static String escape(String text) {
    return text == null ? "" : text.replace("|", "\\|").replace("\n", " ");
  }
}
